version: "3.9"

services:
  collabora:
    image: collabora/code:latest
    container_name: collabora
    restart: always
    privileged: true
    environment:
      # Allow WOPI hosts: all subdomains of reef.lat, reef.lat, and localhost
      aliasgroup1: "https://.*\\.reef\\.lat:443,https://reef.lat:443,https://localhost:443,http://localhost:80"

      # Tell CODE there's a reverse proxy (used in coolwsd config)
      server_name: "https://office.reef.lat"

      # Disable SSL inside CODE (we terminate TLS at nginx)
      extra_params: "--o:ssl.enable=false"

      # Admin console (change for production)
      username: "admin"
      password: "reeflatcom"

      # Optional dictionaries (adjust as needed)
      dictionaries: "en_US es_ES fr_FR"
    networks:
      - collabora_net
    

  nginx:
    image: nginx:stable-alpine
    container_name: collabora-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - collabora
    networks:
      - collabora_net

  certbot:
    image: certbot/certbot
    container_name: collabora-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: ["sh", "-c", "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/certbot --quiet --deploy-hook 'nginx -s reload' || true; done"]
    networks:
      - collabora_net

networks:
  collabora_net:
    driver: bridge
