services:
  collabora:
    image: collabora/code:latest
    container_name: collabora
    restart: always
    privileged: true              # consider removing if not required
    environment:
      aliasgroup1: "https://.*\\.reef\\.lat:443,https://reef.lat:443,https://localhost:443,http://localhost:80"
      server_name: "https://office.reef.lat"   # verify format with CODE docs (might expect hostname only)
      extra_params: "--o:ssl.enable=false"
      username: "admin"
      password: "reeflatcom"      # don't store this in repo for production
      dictionaries: "en_US es_ES fr_FR"
    networks:
      - collabora_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9980/lool/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5

  wopi:
    build: ./wopi
    container_name: wopi_app
    env_file: ./wopi/.env
    expose:
      - "5000"
    restart: unless-stopped
    networks:
      - collabora_net

  nginx:
    image: nginx:stable-alpine
    container_name: collabora-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - collabora
      - wopi
    networks:
      - collabora_net

  certbot:
    image: certbot/certbot
    container_name: collabora-certbot
    restart: unless-stopped
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: ["sh", "-c", "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/certbot --quiet || true; done"]
    networks:
      - collabora_net

networks:
  collabora_net:
    driver: bridge
